### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by vasilich6107** [techniboogie-dart/recase#10]
Here is a screenshots
- https://tppr.me/TnQYK
- https://tppr.me/tVWNe

The performance of recase regex's adds a lot to the rendering time.
Are there any techniques for improving performance?

**Comment by nitehogg** [comment]
Maybe...but just curious, how are you using the library?

**Comment by vasilich6107** [comment]
```
extension DestinationExt on DestinationMixin {
  String get nameTitleCase => ReCase(this.name).titleCase;
}
```

Then there is a listview with 20 items which uses `nameTitleCase`

**Comment by nitehogg** [comment]
So if I'm understanding correctly, you're seeing 20 items taking 3.61ms each, to get their casing updated?
...so 72.2ms overall?

**Comment by vasilich6107** [comment]
To clarify the issue I created as simple example as possible

A `ListView` with 20 items and `rebuild` button to check the performance
```
Scaffold(
      body: Column(
        children: <Widget>[
          Expanded(
            child: ListView.builder(
              itemBuilder: (_, __) =>
                  Text(ReCase('This is-Some_sampleText. YouDig?').titleCase),
              itemCount: 20,
            ),
          ),
          RaisedButton(
            onPressed: () => setState(() {}),
            child: Text('rebuild'),
          )
        ],
      ),
    )
```

Here is a screenshot from profiler - https://tppr.me/hqik7
`hasMatch` operations take 16ms(78%) of the overall UI time

The longer text is more time it takes
The same example with 7 times longer text - https://tppr.me/HH6ma

**Comment by vasilich6107** [comment]
`RegEx` are pretty slow in dart.
https://github.com/dart-lang/sdk/issues/23249

If you replace 

`final RegExp _symbolRegex = new RegExp(r'[ ./_\-]');`
with
`final symbolList = [' ', '.', '/', '_', '\\', '-'];`

and

`_symbolRegex.hasMatch(char)`
with
`symbolList.contains(char)`

It lowers the usage of `hasMatch` significantly and improves performance in two times.
https://tppr.me/zWoAp
The same 20 items list view takes 9 instead 16 ms for `hasMatch` operations

**Comment by vasilich6107** [comment]
The uppercase `hasMatch` could be replaces by something like
`!isAllCaps && nextChar.toUpperCase() == nextChar && nextChar != '?'`

`nextChar != '?'` is not the best solution but it is quick one to make tests run and to test performance improvements.

**Comment by vasilich6107** [comment]
The overall outcome - avoid `regex` in dart at all cost.

**Comment by vasilich6107** [comment]
`bool isAllCaps = !text.contains(RegExp('[a-z]'));`

could be replaced with

`bool isAllCaps = text.toUpperCase() == text;`

Without failing any tests

**Comment by vasilich6107** [comment]
That will be the last `RegExp`)

**Comment by vasilich6107** [comment]
All efforts give us a win from 16ms to 0.4
https://tppr.me/xX3lm

**Comment by mraleph** [comment]
Note that `RegExp` performance was significantly (~5-15x depending on regexp and input string) improved on Flutter master channel (by this change dart-lang/sdk@2c922ba59c3f59843c6785fcf72993764d004776).

Running microbenchmark:

```dart
import 'package:recase/recase.dart';

void main() {
  final sw = Stopwatch()..start();
  var result = null;
  const N = 10000;
  for (var i = 0; i < N; i++) {
    result = ReCase('This is-Some_sampleText. YouDig?').titleCase;
  }
  print('done in ${sw.elapsedMilliseconds} (${sw.elapsedMilliseconds / N} ms. per iteration)');
  print('$result');
}
```

on stable vs master gives the following results:

```
# stable
[+4815 ms] I/flutter (21110): done in 4467 (0.4467 ms. per iteration)

# master
[ +790 ms] I/flutter (21243): done in 429 (0.0429 ms. per iteration)
```

**Comment by vasilich6107** [comment]
@mraleph Did you try the same microbenchmark without regex's?

Without regex it would take ~x4 time less
```
# latest master
done in 108 (0.0108 ms. per iteration)
```

using the `symbolMap` will increase the performance
```
  final symbolMap = {
    ' ': true,
    '.': true,
    '/': true,
    '_': true,
    '\\': true,
    '-': true
  };
```

```
# latest master
done in 87 (0.0087 ms. per iteration)
```

So we have the next per iteration results 
with regex `0.0429 ms`
without regex `0.0087 ms`
~x5 times faster

**Comment by nitehogg** [comment]
Success criteria: 0.0000ms

**Comment by vasilich6107** [comment]
You can leave it "as is")
It is your package)

I achieved that criteria by removing `ReCase` from deps)))

**Comment by nitehogg** [comment]
I just think removing regex completely will introduce less desirable code, if it's even possible to achieve the same things provided by regex, for little gain. 

I'm working on updates now, and I have pulled in some of your suggestions. I think I'm left with one regex, and I have it set so that it's possible that the logic will short-circuit before hitting it. In the end regex may just be a necessary evil. It's a powerful tool, so it should be expected that it takes a little more time to run. More involved logic usually results in longer execution time.

Good luck maintaining an app that achieves 0.0000ms execution time.

**Comment by vasilich6107** [comment]
I know that lib maintenance is hard)
That’s why I’m posting possible workarounds for performance improvement.

**Comment by mraleph** [comment]
> @mraleph Did you try the same microbenchmark without regex's?

No, I did not. My sole point was just to notify of regex improvements - I have not looked at the library source or made any statements about whether or not regex is a good choice for this particular use case.

You are right that regex is not necessarily the fastest way for this particular use-case. If you only care about ASCII you can speed things up quite a bit by avoiding allocating new strings and doing upper/lower case conversions by hand e.g. [like this](https://gist.github.com/mraleph/bbd8a6edf173d0050d56d34459043cff) - this goes around 0.0026 ms. per conversion, but would not properly handle anything outside ASCII.
