### ISSUE TITLE
Snake case unexpected behavior

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [techniboogie-dart/recase#16]
```dart
    final data = jsonEncode({
      "name": "Moh",
      "nationalId": "12345678912345",
    });

    print(ReCase(data).snakeCase);
```
results
```dart 
{"name":"_moh","national_id":"12345678912345"}
```
Look what happened to the ```name``` value, it should be the same as original value ```Moh```, It Unexpectedly is converted to ```_moh```

**Comment by vasilich6107** [comment]
This library was tested to recase only individual strings not complex json serialized objects
