### ISSUE TITLE
Failing to format all uppercase words

### ISSUE THREAD

**Issue by jaripekkala** [techniboogie-dart/recase#3]
```dart
String word = 'FOO_BAR';
String niceWord = ReCase(word).camelCase;
```

I would expect the `word` to be `fooBar` instead of `fOOBAR`.

A workaround is casting the `word` to lowercase before formatting.

**Comment by nitehogg** [comment]
Thanks for the notice. I just pushed an update (2.0.1).

**Comment by jaripekkala** [comment]
Thank you for the quick fix!
